camping/routes/web.php
<?php

Route::get('/', 'PagesController@index');
Route::resource('posts', 'PostController');
Route::get('post/search', 'PostController@search')->name('posts.search');
Route::get('toggle/{id}', 'PostController@toggleActivePost')->name('post.toggleActivePost');
Route::get('post/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+'); // any letter\ any number\ any dash\ any underscore

Route::get('post', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

Route::get('contact', 'PagesController@getContact'); //go to PagesController and do what's inside getContact()
Route::post('contact', 'PagesController@postContact');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::prefix('password')->group(function() {
    Route::get('/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/reset', 'Auth\ResetPasswordController@reset');
});

Route::prefix('auth')->group(function() {
    Route::get('/login', 'Auth\LoginController@showLoginForm');
    Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController', ['except' => ['create']]);
Route::resource('tags', 'TagController', ['except' => ['create']]);

Route::prefix('reviews')->group(function() {
    Route::post('/{post_id}', ['uses' => 'ReviewsController@store', 'as' => 'reviews.store']);
    Route::get('/{id}/edit', ['uses' => 'ReviewsController@edit', 'as' => 'reviews.edit']);
    Route::put('/{id}', ['uses' => 'ReviewsController@update', 'as' => 'reviews.update']);
    Route::delete('/{id}', ['uses' => 'ReviewsController@destroy', 'as' => 'reviews.destroy']);
    Route::get('/{id}/delete', ['uses' => 'ReviewsController@delete', 'as' => 'reviews.delete']);
});

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
});

Route::get('/users', 'UserController@index');
Route::resource('users', 'UserController');
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');

camping/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function posts() {
        return $this->hasmany('App\Post'); //User has many posts
    }
}

camping/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;

class UserController extends Controller
{


    public function __construct()
    {
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();
        return view('users.index')->with('users',$users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    public function destroy(Request $request, $id)
    {
        $user= User::find($id);

        $user->delete();

        $request->session()->flash('success', 'User was deleted successfully');

        return redirect()->route('users.index');
    }
}

camping/resources/views/users/index.blade.php
@extends('layouts.app')

@section('title', '| Edit Users')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>Categories</h1>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                        <th>Email</th>
                        <th>Date</th>
                        <th></th>
                    </tr>
                    </thead>

                    <tbody>

                    @foreach( $users as $user)

                        <tr>
                            <td>{{ $user->id }}</td>
                            <td>{{ $user->name }}</td>
                            <td>{{ $user->email }}</td>
                            <td>{{ date('j F, Y',strtotime($user->created_at)) }}</td>

                            <td>
                                <a href="" class="btn btn-danger btn-block btn-large" onclick="event.preventDefault(); document.getElementById('user-destroy-{{ $user->id }}').submit();">Delete</a>

                                <form id="user-destroy-{{ $user->id }}" action="{{ route('users.destroy', $user->id) }}" method="post" style="display: none;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                </form>

                            </td>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>


@endsection