camping/routes/web.php
<?php

Route::get('/', 'PagesController@index');
Route::resource('posts', 'PostController');
Route::get('post/search', 'PostController@search')->name('posts.search');
Route::get('toggle/{id}', 'PostController@toggleActivePost')->name('post.toggleActivePost');
Route::get('post/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+'); // any letter\ any number\ any dash\ any underscore

Route::get('post', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

Route::get('contact', 'PagesController@getContact'); //go to PagesController and do what's inside getContact()
Route::post('contact', 'PagesController@postContact');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::prefix('password')->group(function() {
    Route::get('/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/reset', 'Auth\ResetPasswordController@reset');
});

Route::prefix('auth')->group(function() {
    Route::get('/login', 'Auth\LoginController@showLoginForm');
    Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController', ['except' => ['create']]);
Route::resource('tags', 'TagController', ['except' => ['create']]);

Route::prefix('reviews')->group(function() {
    Route::post('/{post_id}', ['uses' => 'ReviewsController@store', 'as' => 'reviews.store']);
    Route::get('/{id}/edit', ['uses' => 'ReviewsController@edit', 'as' => 'reviews.edit']);
    Route::put('/{id}', ['uses' => 'ReviewsController@update', 'as' => 'reviews.update']);
    Route::delete('/{id}', ['uses' => 'ReviewsController@destroy', 'as' => 'reviews.destroy']);
    Route::get('/{id}/delete', ['uses' => 'ReviewsController@delete', 'as' => 'reviews.delete']);
});

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
});

Route::get('/users', 'UserController@index');
Route::resource('users', 'UserController');
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');

camping/app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    //tell model to use the categories table
    protected $table = 'categories';

    public function posts() {
        return $this->hasmany('App\Post'); //Category has many posts --> 1 category can have many posts  (Post.php)
    }
}

camping/app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Category;
use Session;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        //display a view of all of the categories and form to create a new category
        $categories = Category::all();
        return view('categories.index')->with('categories',$categories);
    }


    public function create()
    {
        //
    }


    public function store(Request $request)
    {
        //Save a new category and then redirect back to index
        $this->validate($request, array('name' => 'required|max:255'));

        $category = new Category;
        $category->name = $request->name;
        $category->save();

        $request->session()->flash('success', 'New Category has been created');

        return redirect()->route('categories.index');
    }


    public function show($id)
    {
        //
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

camping/resources/views/categories/index.blade.php
@extends('layouts.app')
@section('title', '| All Categories')
@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>Categories</h1>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach( $categories as $category)
                        <tr>
                            <td>{{ $category->id }}</td>
                            <td>{{ $category->name }}</td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <div class="col-md-3 col-md-offset-2">
                <div class="well">
                    <h2>New Category</h2>

                    <form action="{{ route('categories.store') }}" method="post" novalidate>
                        {{ csrf_field() }} {{ method_field('POST') }}
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" name="name">
                            @if($errors->has('name'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('name') }}
                                </div>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-success">Create New Category</button>
                    </form>
                </div>

            </div>
        </div>
    </div>

@endsection