camping/routes/web.php
<?php

Route::get('/', 'PagesController@index');
Route::resource('posts', 'PostController');
Route::get('post/search', 'PostController@search')->name('posts.search');
Route::get('toggle/{id}', 'PostController@toggleActivePost')->name('post.toggleActivePost');
Route::get('post/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+'); // any letter\ any number\ any dash\ any underscore

Route::get('post', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

Route::get('contact', 'PagesController@getContact'); //go to PagesController and do what's inside getContact()
Route::post('contact', 'PagesController@postContact');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::prefix('password')->group(function() {
    Route::get('/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/reset', 'Auth\ResetPasswordController@reset');
});

Route::prefix('auth')->group(function() {
    Route::get('/login', 'Auth\LoginController@showLoginForm');
    Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController', ['except' => ['create']]);
Route::resource('tags', 'TagController', ['except' => ['create']]);

Route::prefix('reviews')->group(function() {
    Route::post('/{post_id}', ['uses' => 'ReviewsController@store', 'as' => 'reviews.store']);
    Route::get('/{id}/edit', ['uses' => 'ReviewsController@edit', 'as' => 'reviews.edit']);
    Route::put('/{id}', ['uses' => 'ReviewsController@update', 'as' => 'reviews.update']);
    Route::delete('/{id}', ['uses' => 'ReviewsController@destroy', 'as' => 'reviews.destroy']);
    Route::get('/{id}/delete', ['uses' => 'ReviewsController@delete', 'as' => 'reviews.delete']);
});

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
});

Route::get('/users', 'UserController@index');
Route::resource('users', 'UserController');
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');

camping/resources/views/partials/_footer.blade.php
<div class="container" id="footer">
    <hr>

    <p class="text-center">Copyright Camping Review - All Rights Reserved</p>
</div>

camping/resources/views/partials/_head.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Camping Review @yield('title')</title>

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css"
      integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
{{--<link rel="stylesheet" href="/css/style.css">--}}
<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Special+Elite" rel="stylesheet">
<link rel="stylesheet" href="{{asset('css/style.css')}}">
<link rel="stylesheet" href="{{asset('css/font-awesome.css')}}">
<link rel="stylesheet" href="{{asset('css/select2.css')}}">

@yield('stylesheet')

camping/resources/views/partials/_javascript.blade.php
<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
<script src="/js/select2.full.min.js"></script>

@yield('scripts')

camping/resources/views/partials/_messages.blade.php
@if (Session::has('success'))
    <div class="container">
        <div class="alert alert-success" role="alert">
            <strong>Success:</strong> {{ Session::get('success') }}
        </div>
    </div>

@endif

@if (count($errors) > 0)
    <div class="container">
        <div class="alert alert-danger" role="alert">
            <strong>Errors:</strong>
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>

                @endforeach
            </ul>
        </div>
    </div>
@endif

camping/resources/views/partials/_nav.blade.php
<nav class="navbar" id="first-nav">
</nav>
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/">Camping Review</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item {{ Request::is('/') ? "active": ""}}">
                <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item {{ Request::is('users') ? "active": ""}}">
                <a class="nav-link" href="/users">Owners</a>
            </li>
            <li class="nav-item {{ Request::is('contact') ? "active": ""}}">
                <a class="nav-link" href="/contact">Contact</a>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            @if (Auth::check())

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Hi {{ Auth::user()->name }}
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{{ route('posts.index') }}">Posts</a>
                        <a class="dropdown-item" href="{{ route('categories.index') }}">Categories</a>
                        <a class="dropdown-item" href="{{ route('tags.index') }}">Tags</a>
                        <a class="dropdown-item" href="{{ route('logout') }}">Log-out</a>
                    </div>
                </li>
            @else
                <a href="{{ route('register') }}" class="btn btn-warning " style="margin-right: 10px" >Register</a>
                <a href="{{ route('login') }}" class="btn btn-primary">Login</a>

            @endif
        </ul>

    </div>
</nav>