camping/routes/web.php
<?php

Route::get('/', 'PagesController@index');
Route::resource('posts', 'PostController');
Route::get('post/search', 'PostController@search')->name('posts.search');
Route::get('toggle/{id}', 'PostController@toggleActivePost')->name('post.toggleActivePost');
Route::get('post/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle'])->where('slug', '[\w\d\-\_]+'); // any letter\ any number\ any dash\ any underscore

Route::get('post', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);

Route::get('contact', 'PagesController@getContact'); //go to PagesController and do what's inside getContact()
Route::post('contact', 'PagesController@postContact');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('logout', 'Auth\LoginController@logout')->name('logout');

Route::prefix('password')->group(function() {
    Route::get('/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('/reset', 'Auth\ResetPasswordController@reset');
});

Route::prefix('auth')->group(function() {
    Route::get('/login', 'Auth\LoginController@showLoginForm');
    Route::get('/register', 'Auth\RegisterController@showRegistrationForm');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController', ['except' => ['create']]);
Route::resource('tags', 'TagController', ['except' => ['create']]);

Route::prefix('reviews')->group(function() {
    Route::post('/{post_id}', ['uses' => 'ReviewsController@store', 'as' => 'reviews.store']);
    Route::get('/{id}/edit', ['uses' => 'ReviewsController@edit', 'as' => 'reviews.edit']);
    Route::put('/{id}', ['uses' => 'ReviewsController@update', 'as' => 'reviews.update']);
    Route::delete('/{id}', ['uses' => 'ReviewsController@destroy', 'as' => 'reviews.destroy']);
    Route::get('/{id}/delete', ['uses' => 'ReviewsController@delete', 'as' => 'reviews.delete']);
});

Route::prefix('admin')->group(function() {
    Route::get('/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
    Route::post('/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
    Route::get('/', 'AdminController@index')->name('admin.dashboard');
    Route::get('/logout', 'Auth\AdminLoginController@logout')->name('admin.logout');
});

Route::get('/users', 'UserController@index');
Route::resource('users', 'UserController');
Route::get('/users/logout', 'Auth\LoginController@userLogout')->name('user.logout');

camping/app/Tag.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    public function posts() {
        return $this->belongsToMany('App\Post'); //Tag has many posts --> post has many tags
    }
}

camping/app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Tag;
use Session;
use App\Post;

class TagController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth', ['except' => 'show']); //only authenticated user are allowed to this controler
    }

    public function index()
    {
        $tags = Tag::all();
        return view('tags.index')->with('tags', $tags);
    }


    public function store(Request $request)
    {
        $this->validate($request, array('name' => 'required|max:255'));
        $tag = new Tag;
        $tag->name = $request->name;
        $tag->save();

        $request->session()->flash('success', 'New Tag was successfully created!');

        return redirect()->route('tags.index');
    }


    public function show($id)
    {
        $post = Post::find($id);
        $tag = Tag::find($id);
        return view('tags.show')->with('tag', $tag, 'post', $post);
    }

    public function edit($id)
    {
        $tag= Tag::find($id);
        return view('tags.edit')->with('tag', $tag);
    }


    public function update(Request $request, $id)
    {
        $tag= Tag::find($id);
        $this->validate($request, ['name' => 'required|max:255']);

        $tag->name = $request->name;
        $tag->save();

        $request->session()->flash('success', 'Successfully saved your new tag');

        return redirect()->route('tags.show', $tag->id);
    }


    public function destroy(Request $request, $id)
    {
        $tag= Tag::find($id);
        $tag->posts()->detach();

        $tag->delete();

        $request->session()->flash('success', 'Tag was deleted successfully');

        return redirect()->route('tags.index');
    }
}

camping/resources/views/tags/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Tags')

@section('content')

    <div class="container">

        <form action="{{ route('tags.update', $tag->id) }}" method="post" novalidate>
            {{ csrf_field() }}
            {{ method_field('PUT') }}
            <div class="form-group">
                <label for="name">Name:</label>
                <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" name="name" value="{{ $tag->name}}">
                @if($errors->has('name'))
                    <div class="invalid-feedback">
                        {{ $errors->first('name') }}
                    </div>
                @endif
            </div>
            <button type="submit" class="btn btn-success">Save Changes</button>
        </form>
    </div>



@endsection

camping/resources/views/tags/index.blade.php
@extends('layouts.app')

@section('title', '| All Tags')

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>Tags</h1>
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Name</th>
                    </tr>
                    </thead>

                    <tbody>

                    @foreach( $tags as $tag)
                        <tr>
                            <td>{{ $tag->id }}</td>
                            <td><a href="{{ route('tags.show', $tag->id ) }}" style="color:black">{{ $tag->name }}</a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            <div class="col-md-3 col-md-offset-2">
                <div class="well">
                    <h2>New Tag</h2>
                    <form action="{{ route('tags.store') }}" method="post" novalidate>
                        {{ csrf_field() }}
                        {{ method_field('POST') }}
                        <div class="form-group">
                            <label for="name">Name:</label>
                            <input type="text" class="form-control{{ $errors->has('name') ? ' is-invalid' : '' }}" id="name" name="name">
                            @if($errors->has('name'))
                                <div class="invalid-feedback">
                                    {{ $errors->first('name') }}
                                </div>
                            @endif
                        </div>
                        <button type="submit" class="btn btn-success">Create New Tag</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

@endsection

camping/resources/views/tags/show.blade.php
@extends('layouts.app')

@section('title', "| $tag->name Tag")

@section('content')

    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <h1>{{ $tag->name }}
                    <small> {{ $tag->posts()->count() }} Posts</small>
                </h1>
            </div>
            @if (Auth::check())
            <div class="col-md-2">
                <a href="{{ route('tags.edit', $tag->id) }}" class="btn btn-primary btn-block" style="float: right;">Edit</a>
            </div>
            <div class="col-md-2">

                <a href="" class="btn btn-danger btn-block" onclick="event.preventDefault(); document.getElementById('tag-destroy-{{ $tag->id }}').submit();">Delete</a>

                <form id="tag-destroy-{{ $tag->id }}" action="{{ route('tags.destroy', $tag->id) }}" method="post" style="display: none;">
                    {{ csrf_field() }}
                    {{ method_field('DELETE') }}
                </form>
            </div>

                @endif
        </div>

        <div class="row">
            <div class="col-md-12">
                <table class="table">
                    <thead>
                    <tr>
                        <th>#</th>
                        <th>Title</th>
                        <th>Tags</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach ($tag->posts as $post)
                        <tr>
                            <th>{{ $post->id }}</th>
                            <td>{{ $post->title }}</td>
                            <td>@foreach ($post->tags as $tag)
                                    <span class="btn btn-primary btn-sm"> {{ $tag->name }}</span>
                                @endforeach
                            </td>
                            <td> <a href="{{ url('post/'.$post->slug) }}" class="btn btn-outline-secondary btn-sm">Read more</a></td>

                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection